
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxkrymooailsmedvtsfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4a3J5bW9vYWlsc21lZHZ0c2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTk0ODksImV4cCI6MjA2Mjc5NTQ4OX0.xEcIICjLGip_5gsvq2ieh2Vhjo4tpiGCJupWF86lU-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);
